service: aws-python-img-ops

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

functions:
  worker:
    handler: handler.start
    environment:
      BUCKET: !Ref Bucket
      REGION: us-east-1
    events:
      - http:
          path: /images
          method: get
      - http:
          path: /images/{image}
          method: get
      - http:
          path: /images/{image}
          method: put
      - http:
          path: /images/{image}
          method: delete

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: "non-linux"